spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: product    
  datasource:
    url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
eureka:  client:    serviceUrl:      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}    
logging:
  level:
    root: DEBUG 