spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: order   
  session:    store-type: redis
  redis:    host: localhost
    port: 6379     
  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
logging:
  level:
    root: INFO      